services:
  fastapi:
    build: 
      dockerfile: dockerfile
    container_name: fastapi-app
    ports:
      - "8005:8005"
    volumes:
      - ./faiss_nursing_homes:/app/faiss_nursing_homes
    env_file:
      - .env
    restart: always