  services:
  fastapi:
    build: 
      dockerfile: dockerfile
    container_name: fastapi-app
    ports:
      - "8005:8005"
    volumes:
      - .:/app
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    restart: always